
server:
  port: 9001
  servlet:
    context-path: /api/nohauth
spring:
  profiles:
    active: dev

#  apps:
#    package: com.xxx.oauth
#    logging:
#      level-info: INFO
#      level-debug: DEBUG
#      level-error: ERROR

  datasource:
#    url: jdbc:mysql://localhost:3306/nohderdb
#    username: nohder
#    password: nohder
    url: jdbc:mysql://localhost:3306/localdb
    username: userlocal
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
#    initialization-mode: never
#    platform: mysql
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true

check-user-scopes: true
